title: File

accept:
    mime:  image/jpeg, image/png, image/svg+xml, image/gif

columns:
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Alternative Text
            type: text
