
title: Pages
icon: page
label: Pages
columns:
  left:
    width: 1/3
    sections:
      listed-pages:
        headline: Listed Pages
        type: pages
        status: listed

  right:
    width: 2/3
    sections:
      unlisted-pages:
        headline: Continents
        type: pages
        layout: cards  
        size: small
        sortBy: title
        image: page.cover.toFile
          back: white
        status: unlisted
        template:
         - continent 